config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  resources :allies, only: :index do
    collection do
      post 'add'
      post 'remove'
    end
  end

  resources :comment, only: [:create, :destroy] do
    collection do
      post 'create'
      delete 'delete'
    end
  end

  resources :medications

  resources :moods do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :categories do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :moments

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :groups do
    scope module: :groups do
      resource :membership, only: [:create, :destroy] do
        delete ':member_id', to: 'memberships#kick', as: 'kick'
      end
    end
  end

  resources :meetings do
    collection do
      get 'join'
      get 'leave'
    end
  end

  resources :profile, only: :index do
    collection do
      post 'add_ban'
      post 'remove_ban'
    end
  end

  resources :reports, only: [:create, :new] do
    collection do
      get 'admin_dashboard'
    end
  end

  resources :search, only: :index do
    collection do
      get 'posts'
    end
  end

  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'clear'
      get 'fetch_notifications'
      get 'signed_in'
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'admin_dashboard', to: 'pages#admin_dashboard', via: :get
  match 'contribute', to: 'pages#contribute', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :post
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, controllers: { registrations: :registrations,
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       invitations: 'users/invitations',
                                       sessions: :sessions }

  post 'pusher/auth'

  Rails.configuration.i18n.available_locales.each do |locale|
    get locale.to_s => 'locales#set_initial_locale', defaults: { locale: locale.to_s }
  end

  root 'pages#home'
end

app/controllers/allies_controller.rb
# frozen_string_literal: true

class AlliesController < ApplicationController
  # GET /allies
  # GET /allies.json
  def index
    @page_search = true
    @accepted_allies = current_user.allies_by_status(:accepted)
                                   .sort_by! { |n| n.name.downcase }
    @incoming_ally_requests = current_user.allies_by_status(:pending_from_user)
                                          .sort_by! { |n| n.name.downcase }
    @outgoing_ally_requests = current_user.allies_by_status(:pending_from_ally)
                                          .sort_by! { |n| n.name.downcase }
    @invited_allies = User.where(
      invited_by_id: current_user.id, invitation_accepted_at: nil
    )
  end

  def add
    AllyshipCreator.perform(ally_id: params[:ally_id],
                            current_user: current_user)
    redirect_to_path(allies_path)
  end

  def remove
    user_id = current_user.id
    ally_id = params[:ally_id].to_i
    Allyship.where(user_id: user_id, ally_id: ally_id).destroy_all
    redirect_to_path(allies_path)
  end
end

app/views/allies/index.html.erb
<% title t('allies.index.title') %>
<%= render partial: '/search/form' %>
<%= link_to t('allies.index.invite'), new_user_invitation_path, class: 'smallMarginTop buttonDarkM fullWidth center' %>

<% if @outgoing_ally_requests.any? %>
  <div class="marginTop">
    <div class="title"><%= t('allies.index.outgoing') %></div>
    <div class="gridThree">
    <% @outgoing_ally_requests.each do |ally| %>
      <div class="gridThreeItemBoxLight ally">
        <%= link_to ProfilePicture.fetch(ally.avatar.url, name: ally.name), profile_index_path(uid: ally.uid) %>
        <div class="subtle"><%= ally.location %></div>
        <%= link_to t('allies.index.cancel'), remove_allies_path(ally_id: ally.id), method: :post, data: { confirm: t('common.actions.confirm') } %>
      </div>
    <% end %>
    </div>
  </div>
<% end %>

<% if @incoming_ally_requests.any? %>
  <div class="marginTop">
    <div class="title"><%= t('allies.index.incoming') %></div>
    <div class="gridThree">
    <% @incoming_ally_requests.each do |ally| %>
      <div class="gridThreeItemBoxLight ally">
        <%= link_to ProfilePicture.fetch(ally.avatar.url, name: ally.name), profile_index_path(uid: ally.uid) %>
        <div class="subtle"><%= ally.location %></div>
        <%= link_to t('allies.accept'), add_allies_path(ally_id: ally.id), method: :post %> | <%= link_to t('common.actions.remove'), remove_allies_path(ally_id: ally.id), method: :post, data: { confirm: t('common.actions.confirm') } %>
      </div>
    <% end %>
    </div>
  </div>
<% end %>
<% if @invited_allies.any? %>
  <div class="marginTop">
  <div class="title"><%= t('allies.index.invited') %></div>
  <div class="gridThree">
  <% @invited_allies.each do |ally| %>
    <div class="gridThreeItemBoxLight ally">
      <div><%= mail_to "#{ally.email}" %></div>
      <div class="subtle"><%=t('allies.index.invited_on', date: format_date(ally.invitation_sent_at)) %></div>
      <div class="subtle"><%= ally.invitation_sent_at < 2.weeks.ago ? t('allies.index.invitation_expired') : nil %></div>
    </div>
  <% end %>
  </div>
<% end %>
<% if @accepted_allies.present? %>
  <div class="marginTop">
    <div class="title"><%= t('allies.index.title') %></div>
    <div class="gridThree">
      <% @accepted_allies.each do |ally| %>
        <div class="gridThreeItemBoxLight ally">
          <%= link_to ProfilePicture.fetch(ally.avatar.url, name: ally.name), profile_index_path(uid: ally.uid) %>
          <div class="subtle"><%= ally.location %></div>
          <div>
            <%= link_to t('common.actions.remove'), remove_allies_path(ally_id: ally.id), method: :post, data: { confirm: t('common.actions.confirm') } %>
          </div>
          <div>
            <%= link_to t('common.actions.report'), new_report_path(uid: ally.uid) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% if @outgoing_ally_requests.empty? && @incoming_ally_requests.empty? && @accepted_allies.count == 0 %>
  <div class="marginTop">
    <%= t('allies.index.none') %>
  </div>
<% end %>