config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  resources :allies, only: :index do
    collection do
      post 'add'
      post 'remove'
    end
  end

  resources :comment, only: [:create, :destroy] do
    collection do
      post 'create'
      delete 'delete'
    end
  end

  resources :medications

  resources :moods do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :categories do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :moments

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :groups do
    scope module: :groups do
      resource :membership, only: [:create, :destroy] do
        delete ':member_id', to: 'memberships#kick', as: 'kick'
      end
    end
  end

  resources :meetings do
    collection do
      get 'join'
      get 'leave'
    end
  end

  resources :profile, only: :index do
    collection do
      post 'add_ban'
      post 'remove_ban'
    end
  end

  resources :reports, only: [:create, :new] do
    collection do
      get 'admin_dashboard'
    end
  end

  resources :search, only: :index do
    collection do
      get 'posts'
    end
  end

  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'clear'
      get 'fetch_notifications'
      get 'signed_in'
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'admin_dashboard', to: 'pages#admin_dashboard', via: :get
  match 'contribute', to: 'pages#contribute', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :post
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, controllers: { registrations: :registrations,
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       invitations: 'users/invitations',
                                       sessions: :sessions }

  post 'pusher/auth'

  Rails.configuration.i18n.available_locales.each do |locale|
    get locale.to_s => 'locales#set_initial_locale', defaults: { locale: locale.to_s }
  end

  root 'pages#home'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    permitted = params.require(:search).permit(:email)
    raise ActionController::ParameterMissing if permitted.blank?

    @matching_users = search_by_email(permitted[:email].strip)
    @email_query = permitted[:email]
  rescue ActionController::ParameterMissing
    redirect_to_path(allies_path)
  end

  def posts
    data_type = params[:search][:data_type]
    term = params[:search][:name]

    return unless data_type.in?(%w[moment category mood strategy medication])

    redirect_to_path(make_path(term, data_type))
  end

  private

  def search_by_email(email)
    User.where(email: email).where.not(id: current_user.id)
  end

  def make_path(term, data_type)
    send("#{data_type.pluralize}_path", ({ search: term } if term.present?))
  end
end

app/views/search/_form.html.erb
<%= form_for(:search, url: search_index_path, html: { method: :get }) do |f| %>
  <div class="search">
    <% if @email.nil? %>
      <%= f.text_field :email, placeholder: t('search.form.search_by_email'), 'aria-label': t('search.form.search_by_email') %>
    <% else %>
      <%= f.text_field :email, placeholder: t('search.form.search_by_email'), value: @email, 'aria-label': t('search.form.search_by_email') %>
    <% end %>
    <%= f.submit t('search.label'), class: 'searchSubmit' %>
  </div>
<% end %>

app/views/search/_posts.html.erb
<div class="marginBottom">
  <%= form_for(:search, url: posts_search_index_path, html: { method: :get }) do |f| %>
    <div class="search">
      <%= f.text_field :name, placeholder: t('search.search_by_name'), 'aria-label': t('search.search_by_name') %>
      <%= f.hidden_field :data_type, value: local_assigns[:data_type] %>
      <%= f.submit t('search.label'), class: 'searchSubmit' %>
    </div>
  <% end %>
</div>

app/views/search/index.html.erb
<% title t('search.index.title') %>
<%= render 'form' %>
<%= link_to t('allies.index.view_all_allies'), allies_path, class: 'smallMarginTop buttonDarkM fullWidth center' %>
<div class="gridThree marginTop">
  <% if @matching_users.present? %>
    <% @matching_users.each do |user| %>
        <div class="gridThreeItemBoxLight ally">
          <%= link_to ProfilePicture.fetch(user.avatar.url, name: user.name), profile_index_path(uid: user.uid) %>
          <div class="subtle"><%= user.location %></div>
          <% if current_user.allies_by_status(:pending_from_ally).include?(user) %>
            <%= link_to t('allies.cancel_ally_request'), remove_allies_path(ally_id: user.id), method: :post, data: { confirm: t('common.actions.confirm') } %>
          <% elsif current_user.allies_by_status(:pending_from_user).include?(user) %>
            <%= link_to t('allies.accept'), add_allies_path(ally_id: user.id), method: :post %>
          <% elsif current_user.allies_by_status(:accepted).include?(user) %>
            <%= link_to t('common.actions.remove'), remove_allies_path(ally_id: user.id), method: :post, data: { confirm: t('common.actions.confirm') } %>
          <% else %>
            <%= link_to t('allies.add_ally'), add_allies_path(ally_id: user.id), method: :post %>
          <% end %>
        </div>
    <% end %>
  <% else %>
    <%= t('search.index.user_not_found', email: @email_query) %>
  <% end %>
</div>