config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  resources :allies, only: :index do
    collection do
      post 'add'
      post 'remove'
    end
  end

  resources :comment, only: [:create, :destroy] do
    collection do
      post 'create'
      delete 'delete'
    end
  end

  resources :medications

  resources :moods do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :categories do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :moments

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :groups do
    scope module: :groups do
      resource :membership, only: [:create, :destroy] do
        delete ':member_id', to: 'memberships#kick', as: 'kick'
      end
    end
  end

  resources :meetings do
    collection do
      get 'join'
      get 'leave'
    end
  end

  resources :profile, only: :index do
    collection do
      post 'add_ban'
      post 'remove_ban'
    end
  end

  resources :reports, only: [:create, :new] do
    collection do
      get 'admin_dashboard'
    end
  end

  resources :search, only: :index do
    collection do
      get 'posts'
    end
  end

  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'clear'
      get 'fetch_notifications'
      get 'signed_in'
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'admin_dashboard', to: 'pages#admin_dashboard', via: :get
  match 'contribute', to: 'pages#contribute', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :post
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, controllers: { registrations: :registrations,
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       invitations: 'users/invitations',
                                       sessions: :sessions }

  post 'pusher/auth'

  Rails.configuration.i18n.available_locales.each do |locale|
    get locale.to_s => 'locales#set_initial_locale', defaults: { locale: locale.to_s }
  end

  root 'pages#home'
end

app/controllers/concerns/shared.rb
# frozen_string_literal: true
module Shared
  extend ActiveSupport::Concern

  included do
    helper_method :shared_add_premade, :shared_create,
                  :shared_update, :shared_destroy
  end

  def shared_add_premade(model_class, total)
    (1..total).each do |num|
      model_name_plural = model_class.name.pluralize.downcase
      key = "#{model_name_plural}.index.premade#{num}"
      model_class.create(
        user_id: current_user.id,
        name: I18n.t("#{key}_name"),
        description: I18n.t("#{key}_description")
      )
    end
  end

  def shared_quick_create(model_object)
    render json: shared_quick_create_result(model_object)
  end

  def shared_create(model_object)
    action = model_object.save
    create_or_update(action, model_object, false)
  end

  def shared_update(model_object, model_params)
    action = model_object.update(model_params)
    create_or_update(action, model_object, true)
  end

  def shared_destroy(model_object)
    current_user.moments.each do |m|
      update_object(model_object, m)
    end
    if model_object.class == Category
      current_user.strategies.each do |s|
        update_object(model_object, s)
      end
    end
    model_object.destroy
    redirect_to_path(index_path(model_object))
  end

  private

  def index_path(model_object)
    case model_object.class.name
    when 'Mood'
      moods_path
    when 'Category'
      categories_path
    when 'Moment'
      moments_path
    else
      strategies_path
    end
  end

  def show_path(model_object)
    case model_object.class.name
    when 'Mood'
      mood_path(model_object)
    when 'Category'
      category_path(model_object)
    when 'Moment'
      moment_path(model_object)
    else
      strategy_path(model_object)
    end
  end

  def update_object(model_object, object)
    model_name = model_object.class.name.downcase
    object[model_name].delete(model_object.id)
    params = { "#{model_name}": object[model_name] }
    object.class.find_by(id: object.id).update(params)
  end

  def format_success(format, model_object, is_update)
    path = show_path(model_object)
    format.html { redirect_to path }
    status = is_update ? :ok : :created
    format.json { render :show, status: status, location: model_object }
  end

  def format_failure(format, model_object, is_update)
    format.html { render is_update ? :edit : :new }
    format.json do
      render json: model_object.errors, status: :unprocessable_entity
    end
  end

  def create_or_update(action, model_object, is_update)
    respond_to do |format|
      if action
        format_success(format, model_object, is_update)
      else
        format_failure(format, model_object, is_update)
      end
    end
  end

  def shared_quick_create_result(model_object)
    return { success: false } unless model_object.save

    {
      success: true,
      id: model_object.id,
      name: model_object.name,
      slug: model_object.slug
    }
  end
end

app/views/shared/_alerts.erb
<% if notice.present? %>
  <% if current_page?(root_path) %>
    <div class="notice display_none"><%= notice %></div>
  <% else %>
    <div class="notice"><%= notice %></div>
  <% end %>
<% end %>
<% if alert.present? %>
  <% if current_page?(root_path) %>
    <div class="alert display_none"><%= alert %></div>
  <% else %>
    <div class="alert"><%= alert %></div>
  <% end %>
<% end %>

app/views/shared/_alerts.html.erb
<% if notice.present? %>
  <% if current_page?(root_path) %>
    <div class="notice displayNone"><%= notice %></div>
  <% else %>
    <div class="notice"><%= notice %></div>
  <% end %>
<% end %>
<% if alert.present? %>
  <% if current_page?(root_path) %>
    <div class="alert displayNone"><%= alert %></div>
  <% else %>
    <div class="alert"><%= alert %></div>
  <% end %>
<% end %>

app/views/shared/_comments.html.erb
<%= react_component('Comments', props: {
  comments: @comments,
  formProps: comment_form_props(
    local_assigns[:commentable],
    local_assigns[:commentable].class.name.downcase
  )
<<<<<<< HEAD
}) %>
=======
) %>
  <div class="smallMarginTop">
    <%= form_for local_assigns[:comment], url: { action: "comment" }, html: { method: "post" } do |f| %>
      <% if local_assigns[:comment].errors.any? %>
        <div class="errorText">
          <%= t('common.form.error_explanation') %>
        </div>
      <% end %>

      <%= f.text_area :comment, class: 'comment_textarea' %>

      <%= f.hidden_field :commentable_type, value: local_assigns[:commentable_type] %>
      <%= f.hidden_field :comment_by, value: current_user.id %>
      <%= f.hidden_field :commentable_id, value: local_assigns[:data].id %>

      <div class="smallerMarginTop">
        <% if (local_assigns[:commentable_type] == 'moment' || local_assigns[:commentable_type] == 'strategy') && local_assigns[:data].user_id != current_user.id %>
          <%= f.select :visibility, [
            [t('shared.comments.share_everyone'), 'all'],
            [t('shared.comments.share_with', name: User.where(id: local_assigns[:data].user_id).first.name), 'private']
          ] %>
        <% else %>
          <%= f.hidden_field :visibility, value: 'all' %>
          <% if (local_assigns[:commentable_type] == 'moment' || local_assigns[:commentable_type] == 'strategy') && !local_assigns[:data].viewers.blank? && local_assigns[:data].viewers.length > 0 %>
            <%= f.select :viewers, local_assigns[:data].viewers.collect { |v|
              [ t('shared.comments.share_with', name: User.where(id: v).first.name), v ]
            }, include_blank: t('shared.comments.share_everyone') %>
          <% end %>
        <% end %>
      </div>

      <%= f.submit t('comment.singular'), class: 'smallerMarginTop buttonDarkS', id: 'add_comment_button' %>
    </div>
  <% end %>

  <div id="comments">
    <% local_assigns[:comments].each do |comment| %>
      <% if comment.visibility == 'all' ||
        (
          comment.visibility == 'private' &&
          User.where(id: comment.comment_by).exists? &&
          (
            comment.comment_by == current_user.id ||
            local_assigns[:is_member] ||
            current_user.id == local_assigns[:data].user_id ||
            (
              !comment.viewers.blank? &&
              comment.viewers.include?(current_user.id)
            )
          )
        )
      %>
        <% result = generate_comment(comment, comment.commentable_type) %>
        <div class="comment smallMarginTop" id=<%= 'comment_' + comment.id.to_s %>>
          <div class="gridRowSpaceBetween">
            <div class="comment_info">
              <%= raw result[:comment_info] %>
            </div>
            <%= raw result[:delete_comment] %>
            <%= raw result[:report_comment] %>
          </div>
          <div class="comment_text">
            <%= raw result[:comment_text] %>
          </div>
          <div class="subtle">
            <%= raw result[:visibility] %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>
>>>>>>> aaefd3cd... Report block final (#4)

app/views/shared/_common_options.html.erb
<% f = local_assigns[:f] %>
<% all_data = local_assigns[:all_data] %>
<% this_data = local_assigns[:this_data] %>
<% data_type = local_assigns[:data_type] %>
<% data_type_plural = local_assigns[:data_type_plural] %>

<div class="sidebar_field">
  <div class="sidebar_label expand_toggle" data-toggle="<%= "##{data_type_plural}" %>">
    <a href="#" class="toggle_button">
      <i class="fa fa-caret-down"></i>
    </a>
    <%= f.label t("#{data_type_plural}.plural") %>
  </div>

  <div id="<%= data_type_plural %>" class="display_none">

    <% if !all_data.nil? && all_data.length > 0 %>
      <%= f.text_field "#{data_type}_name", data: { autocomplete_source: all_data.map(&:name), autocomplete_source_ids: all_data.map(&:id) }, class: 'full_field smaller_margin_top smaller_margin_bottom' %>
    <% end %>

    <div id="<%= "#{data_type_plural}_list" %>">
      <% all_data.each do |item| %>
        <div id="<%= "#{data_type}_name_#{item.id}" %>" class="<%= this_data.include?(item.id) ? 'display_block' : 'display_none' %>">
          <%= f.check_box(data_type, { multiple: true, checked: this_data.include?(item.id) }, item.id, nil) %>
          <span><%= item.name %></span><br>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_dashboard_nav_actions.html.erb
<div class="dashboardNavActions">
  <%= link_to(t('shared.header.signout'), destroy_user_session_path, method: :delete, class: 'buttonGhostS') %>
</div>

app/views/shared/_dashboard_nav_links.html.erb
<div class="dashboardNavLinks">
  <% if current_user.admin? %>
    <%= dashboard_nav_link_to(t('reports.admin_dashboard'), admin_dashboard_path) %>
  <% end %>
  <%= dashboard_nav_link_to(t('moments.plural'), moments_path) %>
  <%= dashboard_nav_link_to(t('categories.plural'), categories_path) %>
  <%= dashboard_nav_link_to(t('moods.plural'), moods_path) %>
  <%= dashboard_nav_link_to(t('strategies.plural'), strategies_path) %>
  <%= dashboard_nav_link_to(t('medications.index.title'), medications_path) %>
  <%= dashboard_nav_link_to(t('groups.plural'), groups_path) %>
  <%= dashboard_nav_link_to(t('allies.index.title'), allies_path) %>
</div>

app/views/shared/_dashboard_nav_mobile.html.erb
<%= render partial: "shared/dashboard_nav_links" %>
<%= render partial: "shared/dashboard_nav_actions" %>

app/views/shared/_focus.html.erb
<div class="someFocus">
    <div class="someFocusText">
      <% if local_assigns[:data_type] == 'category' && (!local_assigns[:profile] || local_assigns[:profile] ==current_user.id) %>
        <%= viewers_hover(get_viewers_for(Category.where(id: key).first, 'category'), Category.where(id: ke.first) %>
      <% elsif local_assigns[:data_type] == 'category' && local_assigns[:profile] %>
        <div class="someFocusTextName">
          <%= Category.where(id: key).first.name %>
        </div>
      <% elsif local_assigns[:data_type] == 'mood' && (!local_assigns[:profile] || local_assigns[:profile] ==current_user.id) %>
        <%= viewers_hover(get_viewers_for(Mood.where(id: key).first, 'mood'), Mood.where(id: key).first) %>
      <% elsif local_assigns[:data_type] == 'mood' && local_assigns[:profile] %>
        <div class="someFocusTextName">
          <%= Mood.where(id: key).first.name %>
        </div>
      <% elsif local_assigns[:data_type] == 'strategy' && (!local_assigns[:profile] || local_assigns[:profile] ==current_user.id) %>
        <%= viewers_hover(get_viewers_for(Strategy.where(id: key).first, 'strategy'), Strategy.where(id: ke.first) %>
      <% elsif local_assigns[:data_type] == 'strategy' && local_assigns[:profile] %>
        <div class="someFocusTextName">
          <%= Strategy.where(id: key).first.name %>
        </div>
      <% end %>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footerLinks">
    <div>
      <div class="footerLinksTitle"><%= t('app_name') %></div>
      <%= link_to(t('navigation.about'), about_path) %>
      <%= link_to(t('navigation.blog'), 'https://medium.com/ifme') %>
      <%= link_to(t('navigation.contribute'), contribute_path) %>
      <%= link_to(t('navigation.code_of_conduct'), 'https://www.contributor-covenant.org/', target: 'blank') %>
      <%= link_to(t('navigation.faq'), faq_path) %>
      <%= link_to(t('navigation.give_feedback'), 'http://goo.gl/forms/8EqoJDDiXY', target: 'blank') %>
      <%= link_to(t('navigation.partners'), partners_path) %>
      <%= link_to(t('navigation.press'), press_path) %>
      <%= link_to(t('navigation.privacy'), privacy_path) %>
    </div>
    <div>
      <div class="footerLinksTitle"><%= t('shared.footer.connect') %></div>
      <%= link_to(t('common.form.email'), 'mailto:join.ifme@gmail.com') %>
      <%= link_to(t('navigation.facebook'), 'http://facebook.com/ifmeorg', target: 'blank') %>
      <%= link_to(t('navigation.github'), 'https://github.com/ifmeorg/ifme', target: 'blank') %>
      <%= link_to(t('navigation.instagram'), 'https://www.instagram.com/ifmeorg', target: 'blank') %>
      <%= link_to(t('navigation.opencollective'), 'https://opencollective.com/ifme', target: 'blank') %>
      <%= link_to(t('navigation.patreon'), 'http://patreon.com/ifme', target: 'blank') %>
      <%= link_to(t('navigation.rss'), 'https://medium.com/feed/ifme', target: 'blank') %>
      <%= link_to(t('navigation.twitter'), 'http://twitter.com/ifmeorg', target: 'blank') %>
    </div>
  </div>
  <div class="footerExtras">
    <%= react_component('ToggleLocale', props: { locale: @locale, locales: @locales }) %>
    <div>
      <%= sanitize t('shared.footer.licence_subtitle',
        licence: link_to(t('shared.footer.licence'), 'https://github.com/ifmeorg/ifme/blob/master/LICENSE.txt', target: 'blank'))
      %>
    </div>
  </div>
</div>

app/views/shared/_members.html.erb
<% group.members.each do |member| %>
  <div class="gridRowSpaceBetween">
    <%= link_to member.name, profile_index_path(uid: member.uid) %>
    <% if member != current_user &&
      group.instance_of?(Group) &&
      group.leaders.include?(current_user) %>
      <%= kick_member_link(group, member) %>
    <% end %>
  </div>
<% end %>

app/views/shared/_notices_and_alerts.html.erb
<% if notice.present? %>
  <% if current_page?(root_path) %>
    <div class="notice display_none"><%= notice %></div>
  <% else %>
    <div class="notice"><%= notice %></div>
  <% end %>
<% end %>
<% if alert.present? %>
  <% if current_page?(root_path) %>
    <div class="alert display_none"><%= alert %></div>
  <% else %>
    <div class="alert"><%= alert %></div>
  <% end %>
<% end %>

app/views/shared/_page_author.html.erb
<div class="pageAuthor">
  <%= ProfilePicture.fetch(local_assigns[:author].avatar.url, small: true) %>
  <%= link_to local_assigns[:author].name, profile_index_path(uid: local_assigns[:author].uid) %>
</div>

app/views/shared/_page_title.html.erb
<% if !not_signed_in_root_path? %>
  <div class="pageTitle">
  <% if sign_in_path? %>
    <%= t('layouts.application.signin') %>
  <% elsif join_path? %>
    <%= t('layouts.application.create_account') %>
  <% elsif forgot_password_path? %>
    <%= t('account.forgot_password') %>
  <% elsif update_account_path? %>
    <%= t('layouts.application.update_account') %>
  <% elsif send_ally_invitation_path? %>
    <%= t('devise.invitations.new.header') %>
  <% elsif ally_accept_invitation_path? %>
    <%= t('devise.invitations.edit.header') %>
  <% elsif reset_password_path? %>
    <%= t('layouts.title.reset_password') %>
  <% elsif yield(:page_new).present? && @page_new %>
    <div class="pageTitleLeft">
      <%= yield(:title) %>
    </div>
    <div class="pageTitleRight">
      <%= link_to @page_new, yield(:page_new), class: 'buttonM' %>
    </div>
  <% elsif @page_author.present? %>
    <div class="pageTitleLeft">
      <%= yield(:title) %>
    </div>
    <div class="pageTitleRight">
      <%= render partial: '/shared/page_author', locals: { author: @page_author } %>
    </div>
  <% else %>
    <%= yield(:title) %>
  <% end %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% if %w[category mood strategy].include?(local_assigns[:data_type]) %>
  <% most_focus_data = most_focus(local_assigns[:data_type], local_assigns[:user]) %>
	<% if most_focus_data.present? %>
    <div class="stats">
      <% if local_assigns[:user] %>
        <div class="title">
          <%= local_assigns[:data_type].pluralize.titleize %>
        </div>
      <% end %>
      <div class="subtitle">
        <% if local_assigns[:user] == current_user %>
          <%= t('shared.stats.you_are_focusing') %>
        <% elsif local_assigns[:user] %>
          <%= t('shared.stats.user_is_focusing', name: User.where(id: local_assigns[:user]).first.name) %>
        <% end %>
      </div>
      <div class="mostFocus">
        <% most_focus_data.each do |key, value| %>
          <div class="someFocus">
            <div class="someFocusText">
              <% if local_assigns[:data_type] == 'category' && local_assigns[:user] == current_user %>
                <%= viewers_hover(get_viewers_for(Category.where(id: key).first, 'category'), Category.where(id: key).first) %>
              <% elsif local_assigns[:data_type] == 'category' && local_assigns[:user] %>
                <div class="someFocusTextName">
                  <%= Category.find_by(id: key).name %>
                </div>
              <% elsif local_assigns[:data_type] == 'mood' && local_assigns[:user] == current_user %>
                <%= viewers_hover(get_viewers_for(Mood.where(id: key).first, 'mood'), Mood.where(id: key).first) %>
              <% elsif local_assigns[:data_type] == 'mood' && local_assigns[:user] %>
                <div class="someFocusTextName">
                  <%= Mood.find_by(id: key).name %>
                </div>
              <% elsif local_assigns[:data_type] == 'strategy' && local_assigns[:user] == current_user %>
                <%= viewers_hover(get_viewers_for(Strategy.where(id: key).first, 'strategy'), Strategy.where(id: key).first) %>
              <% elsif local_assigns[:data_type] == 'strategy' && local_assigns[:user] %>
                <div class="someFocusTextName">
                  <%= Strategy.find_by(id: key).name %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
	<% end %>
<% elsif local_assigns[:data_type] == 'moment' %>
	<%= sanitize(moments_stats) %>
<% end %>