config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  resources :allies, only: :index do
    collection do
      post 'add'
      post 'remove'
    end
  end

  resources :comment, only: [:create, :destroy] do
    collection do
      post 'create'
      delete 'delete'
    end
  end

  resources :medications

  resources :moods do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :categories do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :moments

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post 'premade'
      post 'quick_create'
    end
  end

  resources :groups do
    scope module: :groups do
      resource :membership, only: [:create, :destroy] do
        delete ':member_id', to: 'memberships#kick', as: 'kick'
      end
    end
  end

  resources :meetings do
    collection do
      get 'join'
      get 'leave'
    end
  end

  resources :profile, only: :index do
    collection do
      post 'add_ban'
      post 'remove_ban'
    end
  end

  resources :reports, only: [:create, :new] do
    collection do
      get 'admin_dashboard'
    end
  end

  resources :search, only: :index do
    collection do
      get 'posts'
    end
  end

  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'clear'
      get 'fetch_notifications'
      get 'signed_in'
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'admin_dashboard', to: 'pages#admin_dashboard', via: :get
  match 'contribute', to: 'pages#contribute', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :post
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, controllers: { registrations: :registrations,
                                       omniauth_callbacks: 'omniauth_callbacks',
                                       invitations: 'users/invitations',
                                       sessions: :sessions }

  post 'pusher/auth'

  Rails.configuration.i18n.available_locales.each do |locale|
    get locale.to_s => 'locales#set_initial_locale', defaults: { locale: locale.to_s }
  end

  root 'pages#home'
end

app/models/strategy.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: strategies
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  category     :text
#  description  :text
#  viewers      :text
#  comment      :boolean
#  created_at   :datetime
#  updated_at   :datetime
#  name         :string
#  slug         :string
#  published_at :datetime
#

class Strategy < ApplicationRecord
  include Viewer
  extend FriendlyId

  friendly_id :name
  serialize :category, Array
  serialize :viewers, Array

  before_save :array_data_to_i!

  belongs_to :user
  has_many :comments, as: :commentable

  has_one :perform_strategy_reminder
  accepts_nested_attributes_for :perform_strategy_reminder

  validates :comment, inclusion: [true, false]
  validates :user_id, :name, :description, presence: true
  validates :description, length: { minimum: 1 }

  scope :published, -> { where.not(published_at: nil) }
  scope :recent, -> { order('created_at DESC') }

  def active_reminders
    [perform_strategy_reminder].select(&:active?) if perform_strategy_reminder
  end

  def array_data_to_i!
    category.map!(&:to_i)
    viewers.map!(&:to_i)
  end

  def published?
    published_at.present?
  end

  def comments
    Comment.comments_from(self)
  end
end

app/controllers/strategies_controller.rb
# frozen_string_literal: true

# rubocop:disable ClassLength
class StrategiesController < ApplicationController
  include CollectionPageSetupConcern
  include ReminderHelper
  include Shared

  before_action :set_strategy, only: %i[show edit update destroy]

  # GET /strategies
  # GET /strategies.json
  def index
    page_collection('@strategies', 'strategy')
  end

  # GET /strategies/1
  # GET /strategies/1.json
  def show
    show_with_comments(@strategy)
  end

  def quick_create
    # Assume all viewers and comments allowed
    viewers = []
    current_user.allies_by_status(:accepted).each do |item|
      viewers.push(item.id)
    end
    strategy = Strategy.new(quick_create_params(viewers))
    shared_quick_create(strategy)
  end

  # GET /strategies/new
  def new
    @viewers = current_user.allies_by_status(:accepted)
    @strategy = Strategy.new
    @categories = current_user.categories.order('created_at DESC')
    @category = Category.new
    @strategy.build_perform_strategy_reminder
  end

  # GET /strategies/1/edit
  def edit
    if @strategy.user_id == current_user.id
      @viewers = current_user.allies_by_status(:accepted)
      @categories = current_user.categories.order('created_at DESC')
      @category = Category.new
      PerformStrategyReminder.find_or_initialize_by(strategy_id: @strategy.id)
    else
      redirect_to_path(strategy_path(@strategy))
    end
  end

  # POST /strategies
  # POST /strategies.json
  def create
    @strategy = Strategy.new(strategy_params.merge(user_id: current_user.id))
    @viewers = current_user.allies_by_status(:accepted)
    @category = Category.new
    @strategy.published_at = Time.zone.now if publishing?
    shared_create(@strategy)
  end

  # POST /strategies
  # POST /strategies.json
  # rubocop:disable MethodLength
  def premade
    category = Category.find_by(name: 'Meditation', user: current_user)
    strategy = Strategy.new(
      user: current_user,
      name: t('strategies.index.premade1_name'),
      description: t('strategies.index.premade1_description'),
      category: category ? [category.id] : nil,
      comment: false
    )
    respond_to do |format|
      if strategy.save
        PerformStrategyReminder.create!(strategy: strategy, active: false)
        format.html { redirect_to strategies_path }
        format.json { render :no_content }
      else
        format.html { redirect_to strategies_path }
        format.json { render_errors(strategy) }
      end
    end
  end
  # rubocop:enable MethodLength

  # PATCH/PUT /strategies/1
  # PATCH/PUT /strategies/1.json
  def update
    @viewers = current_user.allies_by_status(:accepted)
    @category = Category.new
    if publishing? && !@strategy.published?
      @strategy.published_at = Time.zone.now
    elsif saving_as_draft?
      @strategy.published_at = nil
    end
    empty_array_for :viewers, :category
    shared_update(@strategy, strategy_params)
  end

  # DELETE /strategies/1
  # DELETE /strategies/1.json
  def destroy
    shared_destroy(@strategy)
  end

  private

  def render_errors(strategy)
    render json: strategy.errors, status: :unprocessable_entity
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_strategy
    @strategy = Strategy.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to_path(strategies_path)
  end

  def strategy_params
    params.require(:strategy).permit(
      :name, :description, :published_at, :draft,
      :comment, { category: [] }, { viewers: [] },
      perform_strategy_reminder_attributes: %i[active id]
    )
  end

  def publishing?
    params[:publishing] == '1'
  end

  def saving_as_draft?
    params[:publishing] != '1'
  end

  def empty_array_for(*symbols)
    symbols.each do |symbol|
      @strategy[symbol] = [] if strategy_params[symbol].nil?
    end
  end

  def quick_create_params(viewers)
    {
      user_id: current_user.id,
      name: params[:strategy][:name],
      description: params[:strategy][:description],
      category: params[:strategy][:category],
      published_at: Time.zone.now,
      comment: true,
      viewers: viewers
    }
  end
end
# rubocop:enable ClassLength

app/helpers/strategies_helper.rb
# frozen_string_literal: true

module StrategiesHelper
  include FormHelper
  include StrategyFormHelper
  include ViewersHelper

  def new_strategy_props(strategy, viewers)
    new_form_props(
      strategy_form_inputs(strategy, viewers),
      strategies_path
    )
  end

  def quick_create_strategy_props
    quick_create_form_props(
      quick_create_strategy_form_inputs,
      quick_create_strategies_path
    )
  end

  def edit_strategy_props(strategy, viewers)
    edit_form_props(
      strategy_form_inputs(strategy, viewers),
      strategy_path(strategy)
    )
  end

  private

  def strategy_form_inputs(strategy, viewers)
    [
      build_strategy_name(strategy),
      build_strategy_description(strategy),
      build_strategy_category,
      get_viewers_input(viewers, 'strategy', 'strategies', strategy),
      build_strategy_comment(strategy),
      build_strategy_publishing(strategy),
      build_strategy_reminder(strategy).merge(type: 'checkbox'),
      build_strategy_reminder_attributes(strategy)
    ]
  end

  def quick_create_strategy_form_inputs
    [
      build_strategy_name(@strategy),
      build_strategy_description(@strategy)
    ]
  end
end

app/views/strategies/_premade.html.erb
<% if @strategies.blank? %>
  <div id="premade_modal" class="modal">
    <div class="modal-content">
    <span class="close_premade_modal">&times;</span>
      <div id="pages">
      <div class="strategy no_margin_bottom premade-box">
        <h1 class="strategy_name">
          <%= content_tag(:span, '<i class="fa fa-lock"></i>'.html_safe, class: 'yes_title small_margin_right', title: t('comment.control')) %>
          <%= t('strategies.index.premade1_name') %>
        </h1>
        <%= strip_tags(t('strategies.index.premade1_description')[0..150]) %>
        <% if t('strategies.index.premade1_description').length >= 150 %>
          <%= t('ellipsis') %>
        <% end %>
          <%= button_to t('common.actions.premade_add'), premade_strategies_path, class: "confirmbtn actions"%>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/strategies/_strategy.html.erb
<%= render partial: '/stories/moment_or_strategy', locals: { item: strategy } %>

app/views/strategies/edit.html.erb
<% title "#{t('common.actions.edit_instance', instance: @strategy.name)}" %>
<%= react_component('Form', props: edit_strategy_props(@strategy, @viewers)) %>

app/views/strategies/index.html.erb
<% title t('strategies.plural') %>
<% page_new new_strategy_path %>
<div class="subtitle">
  <%= t('strategies.index.subtitle') %>
</div>

<% if @strategies.any? %>
  <%= render partial: '/search/posts', locals: { data_type: 'strategy' } %>
  <%= render partial: '/shared/stats', locals: { data_type: 'strategy', user: current_user } %>
  <div class="gridTwo">
    <%= render @strategies %>
  </div>
  <%= paginate @strategies %>
<% else %>
  <%= raw t('strategies.index.instructions') %>
  <%= button_to t('common.actions.add'), premade_strategies_path, class: 'smallMarginTop buttonDarkS' %>
  <div class="gridTwo marginTop">
    <div class="gridTwoItemBoxLight">
      <%= react_component('Story', html_options: html_options, props: {
        name: t('strategies.index.premade1_name'),
        link: strategies_path,
        actions: {
          viewers: t('comment.control')
        }
      }) %>
    </div>
  </div>
<% end %>

app/views/strategies/new.html.erb
<% title "#{t('strategies.new')}" %>
<%= react_component('Form', props: new_strategy_props(@strategy, @viewers)) %>

app/views/strategies/show.html.erb
<% title @strategy.name %>
<div class="gridRowSpaceBetween">
  <%= react_component('StoryDate', props: {
    date: TimeAgo.created_or_edited(@strategy)
  }) %>
  <% if !@strategy.published? %>
    <%= react_component('StoryDraft', props: {
      draft: !@strategy.published? ?  t('draft') : nil
    }) %>
  <% end %>
</div>
<div class="smallMarginTop">
  <%= react_component('StoryCategories', props: {
    categories: @strategy.category.map{ |item| Category.find(item).name }
  }) %>
</div>

<% if @strategy.description.present? %>
  <div class="smallMarginTop">
    <%= sanitize(@strategy.description) %>
  </div>
<% end %>

<% if @strategy.user_id == current_user.id %>
  <div class="gridItemBoxDark smallMarginTop">
    <div class="gridRowSpaceBetween">
      <div class="gridRowSpaceBetween">
        <div class="smallMarginRight"><%= t('common.actions.plural') %>:</div>
        <%= react_component('StoryActions', props: {
          dark: true,
          actions: {
            edit: {
              link: edit_strategy_path(@strategy),
              name: t('common.actions.edit')
            },
            delete: {
              name: t('common.actions.delete'),
              link: url_for(@strategy),
              dataMethod: 'delete',
              dataConfirm:  t('common.actions.confirm')
            },
            viewers: get_viewer_list(@strategy.viewers, nil)
          }
        }) %>
      </div>
      <%= print_reminders(@strategy) %>
    </div>
  </div>
<% end %>

<% if @strategy.published? && @strategy.comment %>
  <%= render partial: '/shared/comments', locals: { commentable: @strategy } %>
<% end %>

<%= render partial: '/tag_usage/index', locals: { data: @strategy.id, data_type: 'strategy', user_id: @strategy.user_id } %>